definitions:
  dtos.CreateOrderRequest:
    properties:
      product:
        type: string
      quantity:
        type: integer
      userId:
        type: integer
    required:
    - product
    - quantity
    - userId
    type: object
  dtos.CreateOrderResponse:
    properties:
      id:
        type: integer
      product:
        type: string
      quantity:
        type: integer
      userId:
        type: integer
    type: object
  dtos.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  dtos.CreateUserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  dtos.DeleteOrderResponse:
    properties:
      success:
        type: boolean
    type: object
  dtos.DeleteUserResponse:
    properties:
      success:
        type: boolean
    type: object
  dtos.GetAllOrdersResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/dtos.GetOrderResponse'
        type: array
    type: object
  dtos.GetOrderResponse:
    properties:
      id:
        type: integer
      product:
        type: string
      quantity:
        type: integer
    type: object
  dtos.GetUserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  dtos.UpdateOrderRequest:
    properties:
      product:
        type: string
      quantity:
        type: integer
    required:
    - product
    - quantity
    type: object
  dtos.UpdateOrderResponse:
    properties:
      id:
        type: integer
      product:
        type: string
      quantity:
        type: integer
    type: object
  dtos.UpdateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  dtos.UpdateUserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  gormqs.ListResulter-dtos_GetUserResponse:
    properties:
      count:
        type: integer
      list:
        items:
          $ref: '#/definitions/dtos.GetUserResponse'
        type: array
    type: object
  nghttp.Code:
    enum:
    - OK
    - INVALID_ARGUMENT
    - BAD_REQUEST
    - NOT_FOUND
    - ALREADY_EXISTS
    - PERMISSION_DENIED
    - UNAUTHENTICATED
    - FAILED_PRECONDITION
    - OUT_OF_RANGE
    - ABORTED
    - CANCELED
    - RESOURCE_EXHAUSTED
    - TOO_MANY_REQUESTS
    - UNKNOWN
    - DEADLINE_EXCEEDED
    - UNIMPLEMENTED
    - INTERNAL
    - UNAVAILABLE
    - DATA_LOSS
    type: string
    x-enum-varnames:
    - CodeOk
    - CodeInvalidArgument
    - CodeBadRequest
    - CodeNotFound
    - CodeAlreadyExists
    - CodePermissionDenied
    - CodeUnauthenticated
    - CodeFailedPrecondition
    - CodeOutOfRange
    - CodeAborted
    - CodeCanceled
    - CodeResourceExhausted
    - CodeTooManyRequests
    - CodeUnknown
    - CodeDeadlineExceeded
    - CodeUnimplemented
    - CodeInternal
    - CodeUnavailable
    - CodeDataLoss
  nghttp.Response:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/nghttp.Code'
        description: public info will expose to client as json
      data:
        description: wanted info
      message:
        description: summary description
        type: string
      meta:
        additionalProperties: {}
        description: description
        type: object
    type: object
info:
  contact: {}
paths:
  /orders:
    get:
      consumes:
      - application/json
      operationId: get-orders
      parameters:
      - default: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dtos.GetAllOrdersResponse'
                  type: array
              type: object
      summary: get orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      operationId: order-create
      parameters:
      - description: Create Order Request
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.CreateOrderResponse'
              type: object
      summary: create an order
      tags:
      - orders
  /orders/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.DeleteOrderResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: delete an order
      tags:
      - orders
    get:
      consumes:
      - application/json
      operationId: get-order
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.GetOrderResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: get an order by ID
      tags:
      - orders
    put:
      consumes:
      - application/json
      operationId: update-order
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - description: Update Order Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.UpdateOrderResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: update an order
      tags:
      - orders
  /stats:
    get:
      description: Provides runtime statistics such as uptime and other metrics.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: Retrieve application statistics
      tags:
      - stats
  /users:
    get:
      consumes:
      - application/json
      operationId: get-users
      parameters:
      - default: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      - default: count,list
        description: |-
          selects can be "count", "list" or "count,list"
          select to get total count, list data or both
        in: query
        name: selects
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/gormqs.ListResulter-dtos_GetUserResponse'
              type: object
      summary: get users
      tags:
      - users
    post:
      consumes:
      - application/json
      operationId: user-create
      parameters:
      - description: create user request
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.CreateUserResponse'
              type: object
      summary: create an user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.DeleteUserResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: delete an user
      tags:
      - users
    get:
      consumes:
      - application/json
      operationId: get-user
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.GetUserResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: get an user
      tags:
      - users
    put:
      consumes:
      - application/json
      operationId: update-user
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - description: Update user Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/nghttp.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.UpdateUserResponse'
              type: object
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/nghttp.Response'
      summary: update an user
      tags:
      - users
swagger: "2.0"
